=begin
#Mautic API docs

#Auto-generated Swagger documentation.

OpenAPI spec version: 3.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

module SwaggerClient
  VERSION = '1.0.0'
end
